---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
  - linux

registries:
  - type: standard
    ref: v4.333.1 # renovate: depName=aquaproj/aqua-registry

packages:
  - name: cli/cli@v2.69.0
  - name: jqlang/jq@jq-1.7.1
  - name: direnv/direnv@v2.35.0
  - name: pnpm/pnpm@v10.7.0
  - name: suzuki-shunsuke/pinact@v3.0.3
  - name: BurntSushi/ripgrep@14.1.1
  - name: junegunn/fzf@v0.61.1
  - name: ducaale/xh@v0.24.0
